In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, cross_validate
from sklearn.preprocessing import MinMaxScaler
from xgboost import XGBRegressor

In [5]:
in_data = pd.read_csv('dataset/dataset_in.txt', index_col=0)
out_dat = pd.read_csv('dataset/dataset_out.txt', index_col=0)
data = pd.concat([in_data, out_dat], axis=1)
data.head()

,P1,Q1,P2,Q2,P3,Q3,P4,Q4,P5,Q5,...,I4_5,I5_6,I7_8,I8_3,I8_9,I9_10,I10_11,I12_13,PERD,QGEN7
day1_min0003,5.5235,2.72529,0.0,0.0,0.150708,0.060212,0.110339,0.068694,-0.338732,0.11529,...,0.321238,0.308236,0.336078,0.149694,0.125453,0.035229,0.032739,0.010088,2.58,0.11
day1_min0008,5.5235,2.72529,0.0,0.0,0.150708,0.060212,0.110339,0.068694,-0.338978,0.11529,...,0.321216,0.308213,0.336078,0.149694,0.125472,0.035251,0.032762,0.010090,2.58,0.11
day1_min0013,5.4248,2.66419,0.0,0.0,0.148893,0.059087,0.107499,0.066933,-0.343748,0.11233,...,0.319803,0.307139,0.335563,0.149652,0.126674,0.035548,0.033110,0.009826,2.54,0.11
day1_min0018,5.3261,2.60299,0.0,0.0,0.147077,0.057961,0.104659,0.065172,-0.348518,0.10937,...,0.318391,0.306066,0.335049,0.149610,0.127876,0.035854,0.033467,0.009564,2.50,0.11
day1_min0023,5.1700,2.50953,0.0,0.0,0.143958,0.056194,0.100389,0.062528,-0.355678,0.10494,...,0.316271,0.304455,0.334275,0.149556,0.129832,0.036413,0.034025,0.009172,2.44,0.11

**HISTOGRAMAS COLUMNAS**

In [3]:
data.loc[:,'P1':'Q14']

,P1,Q1,P2,Q2,P3,Q3,P4,Q4,P5,Q5,...,P10,Q10,P11,Q11,P12,Q12,P13,Q13,P14,Q14
day1_min0003,5.5235,2.72529,0.0,0.0,0.150708,0.060212,0.110339,0.068694,-0.338732,0.115290,...,-0.379584,0.080475,0.084677,0.052634,5.5235,2.72529,0.010719,0.002177,0.163652,0.055362
day1_min0008,5.5235,2.72529,0.0,0.0,0.150708,0.060212,0.110339,0.068694,-0.338978,0.115290,...,-0.379830,0.080475,0.084677,0.052634,5.5235,2.72529,0.010719,0.002177,0.163652,0.055362
day1_min0013,5.4248,2.66419,0.0,0.0,0.148893,0.059087,0.107499,0.066933,-0.343748,0.112330,...,-0.382970,0.078530,0.082500,0.051285,5.4248,2.66419,0.010719,0.002177,0.162291,0.054518
day1_min0018,5.3261,2.60299,0.0,0.0,0.147077,0.057961,0.104659,0.065172,-0.348518,0.109370,...,-0.386110,0.076585,0.080322,0.049935,5.3261,2.60299,0.010719,0.002177,0.160929,0.053674
day1_min0023,5.1700,2.50953,0.0,0.0,0.143958,0.056194,0.100389,0.062528,-0.355678,0.104940,...,-0.390932,0.073645,0.077054,0.047909,5.1700,2.50953,0.010667,0.002166,0.158345,0.052297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
day365_min1418,13.3010,4.57586,0.0,0.0,0.353937,0.116318,0.104602,0.073900,-0.138720,0.037521,...,0.111648,0.107467,0.112103,0.065242,3.5266,2.56590,0.000000,0.000000,0.296255,0.096213
day365_min1423,2.0077,1.30737,0.0,0.0,0.189778,0.100263,0.250440,0.108936,-0.132987,0.133386,...,-0.196286,0.017516,0.434346,0.144337,8.7940,3.81639,0.014380,0.004330,0.188551,0.077220
day365_min1428,4.1573,1.42656,0.0,0.0,0.273387,0.097394,-0.001227,0.045005,-0.242036,0.124459,...,-0.150328,0.091699,-0.002725,0.001395,3.2458,2.18187,0.005476,0.000000,0.294835,0.097520
day365_min1433,4.7262,2.68930,0.0,0.0,0.087053,0.038264,0.160261,0.084288,-0.329360,0.111842,...,-0.322493,0.083923,0.333041,0.117327,7.0012,3.29220,0.016089,0.005491,0.179560,0.074390
day365_min1438,1.2940,1.95958,0.0,0.0,0.001455,0.028393,-0.000251,0.021362,-0.464480,0.153677,...,-0.480963,0.081761,0.024782,0.039762,4.6451,2.64550,0.007871,0.000387,0.334111,0.154507

In [4]:
data.loc[:,'V1':'QGEN7']

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,I4_5,I5_6,I7_8,I8_3,I8_9,I9_10,I10_11,I12_13,PERD,QGEN7
day1_min0003,1.0,0.9888,0.9884,0.9882,0.9882,0.9881,0.9879,0.9883,0.9883,0.9883,...,0.321238,0.308236,0.336078,0.149694,0.125453,0.035229,0.032739,0.010088,2.58,0.11
day1_min0008,1.0,0.9888,0.9884,0.9882,0.9882,0.9881,0.9879,0.9883,0.9883,0.9883,...,0.321216,0.308213,0.336078,0.149694,0.125472,0.035251,0.032762,0.010090,2.58,0.11
day1_min0013,1.0,0.9890,0.9887,0.9885,0.9884,0.9884,0.9882,0.9886,0.9885,0.9885,...,0.319803,0.307139,0.335563,0.149652,0.126674,0.035548,0.033110,0.009826,2.54,0.11
day1_min0018,1.0,0.9893,0.9889,0.9888,0.9887,0.9887,0.9884,0.9889,0.9888,0.9888,...,0.318391,0.306066,0.335049,0.149610,0.127876,0.035854,0.033467,0.009564,2.50,0.11
day1_min0023,1.0,0.9897,0.9894,0.9892,0.9891,0.9891,0.9889,0.9893,0.9892,0.9892,...,0.316271,0.304455,0.334275,0.149556,0.129832,0.036413,0.034025,0.009172,2.44,0.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
day365_min1418,1.0,0.9697,0.9692,0.9689,0.9689,0.9688,0.9686,0.9690,0.9690,0.9690,...,0.359258,0.346750,0.360209,0.152221,0.116512,0.023606,0.030831,0.013753,4.20,0.10
day365_min1423,1.0,0.9914,0.9908,0.9905,0.9904,0.9904,0.9901,0.9906,0.9905,0.9905,...,0.388103,0.358683,0.366069,0.158198,0.096359,0.053483,0.036279,0.051589,4.69,0.00
day365_min1428,1.0,0.9908,0.9904,0.9901,0.9901,0.9900,0.9898,0.9903,0.9902,0.9902,...,0.327616,0.327722,0.346114,0.184667,0.145976,0.016711,0.018799,0.000273,3.06,0.00
day365_min1433,1.0,0.9856,0.9852,0.9850,0.9849,0.9848,0.9846,0.9851,0.9850,0.9850,...,0.369724,0.330962,0.334213,0.162891,0.164662,0.205821,0.002388,0.105743,2.93,0.00
day365_min1438,1.0,0.9977,0.9974,0.9972,0.9972,0.9971,0.9969,0.9974,0.9973,0.9973,...,0.771225,0.595791,0.369814,0.202835,0.377774,0.799740,0.009380,0.402384,1.95,0.11

**ESTADÍSTICAS DE LAS COLUMNAS**

In [6]:
data.loc[:,'P1':'Q14'].describe()

,P1,Q1,P2,Q2,P3,Q3,P4,Q4,P5,Q5,...,P10,Q10,P11,Q11,P12,Q12,P13,Q13,P14,Q14
count,105120.000000,105120.000000,105120.0,105120.0,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,...,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000
mean,11.098404,5.469045,0.0,0.0,0.290809,0.125009,0.227800,0.139742,0.273489,0.234254,...,0.217415,0.164508,0.174992,0.106921,11.090266,5.499153,0.019658,0.004925,0.313879,0.117723
std,5.745836,2.326438,0.0,0.0,0.137854,0.056921,0.148469,0.065790,0.312760,0.110520,...,0.238280,0.074398,0.113659,0.050511,5.753923,2.330196,0.011967,0.004866,0.151470,0.061377
min,0.000000,0.000000,0.0,0.0,-0.019101,0.000000,-0.023050,0.000000,-1.225769,0.000000,...,-0.717525,0.000000,-0.013280,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.703775,3.555333,0.0,0.0,0.188544,0.083639,0.113639,0.089007,0.072282,0.149029,...,0.092603,0.107036,0.087253,0.067751,6.692475,3.598130,0.010553,0.000000,0.200824,0.072707
50%,11.124650,5.877230,0.0,0.0,0.292954,0.126241,0.224187,0.146364,0.290950,0.245841,...,0.243368,0.172492,0.172571,0.112161,11.111400,5.888120,0.019174,0.003925,0.312646,0.111775
75%,15.222200,7.248665,0.0,0.0,0.390260,0.164924,0.331287,0.188217,0.488337,0.315357,...,0.377067,0.219896,0.254835,0.144232,15.193725,7.276785,0.028099,0.008081,0.422035,0.158711
max,34.122600,12.283960,0.0,0.0,0.875379,0.361677,0.886436,0.367964,1.397621,0.600764,...,0.968517,0.414780,0.651550,0.275004,33.862300,12.502950,0.068277,0.031953,0.885354,0.392672

In [7]:
data.loc[:,'V1':'QGEN7'].describe()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,I4_5,I5_6,I7_8,I8_3,I8_9,I9_10,I10_11,I12_13,PERD,QGEN7
count,105120.0,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,...,105120.000000,105120.000000,105120.000000,105116.000000,105118.000000,105119.000000,104445.000000,104651.000000,105120.000000,105120.000000
mean,1.0,0.973838,0.973058,0.972682,0.972621,0.972541,0.972306,0.972768,0.972685,0.972679,...,0.458687,0.418206,0.362122,0.156867,0.113689,0.141983,0.038313,0.068913,-6.897002,0.083140
std,0.0,0.013935,0.014075,0.014140,0.014146,0.014152,0.014161,0.014148,0.014150,0.014152,...,0.116138,0.078841,0.025695,0.036332,0.085698,0.198771,0.034079,0.103199,427.595797,0.053139
min,1.0,0.909800,0.908700,0.908300,0.908200,0.908100,0.907800,0.908400,0.908300,0.908300,...,0.224140,0.221765,0.006996,0.000151,0.000391,0.000244,0.000001,0.000005,-25718.990000,-0.130000
25%,1.0,0.964000,0.963100,0.962700,0.962600,0.962575,0.962300,0.962800,0.962700,0.962700,...,0.393426,0.370580,0.343488,0.148933,0.066069,0.048054,0.004605,0.016390,4.940000,0.040000
50%,1.0,0.974100,0.973300,0.973000,0.972900,0.972800,0.972600,0.973000,0.973000,0.972900,...,0.439620,0.408324,0.361687,0.151763,0.095797,0.080430,0.034325,0.030990,8.000000,0.100000
75%,1.0,0.984600,0.984000,0.983700,0.983600,0.983500,0.983300,0.983800,0.983700,0.983700,...,0.485934,0.446215,0.379622,0.156881,0.127388,0.118735,0.064216,0.070157,10.350000,0.130000
max,1.0,1.031100,1.034300,1.035100,1.035000,1.034900,1.034700,1.036500,1.035400,1.035400,...,1.065095,0.836157,0.475546,2.856763,2.761680,1.074079,0.509081,0.542979,57.400000,0.150000

**TRATAMIENTO INICIAL DATOS**

In [ ]:
np.random.seed(357823)

In [1]:
attributes = data.iloc[:, :-28].drop(columns=['P2', 'Q2'])
objectives = data.iloc[:, 28:].drop(columns=['I0_1', 'I0_12', 'I1_2', 'I2_3', 'I3_4', 'I4_5', 'I5_6', 'I7_8', 'I8_3', 'I8_9', 'I9_10', 'I10_11', 'I12_13']) #TODO: INCLUIR CORRIENTE Y TRATAR NAN

NameError: name 'data' is not defined

In [ ]:
normalizer = MinMaxScaler(feature_range=(0, 1))
attributes = pd.DataFrame(normalizer.fit_transform(attributes), columns=attributes.columns)

**ENTRENAMIENTO MODELOS INICIALES**

MODELO 1

In [ ]:
model1 = RandomForestRegressor(n_estimators=50, max_depth=15, min_samples_split=5)
results1 = cross_validate(model1, attributes, objectives, scoring=['neg_mean_absolute_error', 'r2'], cv=10, n_jobs=-1)
print('MSE: ' + str(-results1['test_neg_mean_absolute_error'].mean()))
print('R2: ' + str(results1['test_r2'].mean()))

MODELO 2

In [ ]:
attributes1 = data.iloc[:, :-28].drop(columns=['P2', 'Q2'])
objectives1 = data.iloc[:, -1:]
attributes2 = pd.concat([attributes1, objectives1], axis=1)
objectives2 = data.iloc[:, 28:-1].drop(columns=['I0_1', 'I0_12', 'I1_2', 'I2_3', 'I3_4', 'I4_5', 'I5_6', 'I7_8', 'I8_3', 'I8_9', 'I9_10', 'I10_11', 'I12_13'])

In [ ]:
model2_1 = RandomForestRegressor(n_estimators=50, max_depth=15, min_samples_split=5)
results2_1 = cross_validate(model2_1, attributes1, objectives1, scoring=['neg_mean_absolute_error', 'r2'], cv=10, n_jobs=-1, return_estimator=True)
print('MSE: ' + str(-results2_1['test_neg_mean_absolute_error'].mean()))
print('R2: ' + str(results2_1['test_r2'].mean()))
model2_2 = RandomForestRegressor(n_estimators=50, max_depth=15, min_samples_split=5)
results2_2 = cross_validate(model2_2, attributes2, objectives2, scoring=['neg_mean_absolute_error', 'r2'], cv=10, n_jobs=-1, return_estimator=True)
print('MSE: ' + str(-results2_2['test_neg_mean_absolute_error'].mean()))
print('R2: ' + str(results2_2['test_r2'].mean()))

In [ ]:
model2_1_best = results2_1['estimator'][2]
model2_2_best = results2_2['estimator'][6]

EXPERIMENTO CON PRUEBA ALEATORIA

In [ ]:
example_in = attributes2.iloc[30].to_frame().T.iloc[:, :-1]
example_out = objectives2.iloc[30].to_frame().T
example_out

In [ ]:
attributes2.iloc[30].to_frame().T.iloc[:, -1:]

In [ ]:
example_prediction1 = model2_1_best.predict(example_in)
tmp = pd.DataFrame(example_prediction1, columns=['QGEN7'], index=example_in.index) #Cambiar a -5.1474
example_in_2 = pd.concat([example_in, tmp], axis=1)
tmp

In [ ]:
pd.DataFrame(model2_2_best.predict(example_in_2), columns=example_out.columns, index=example_out.index)

**Modelos con XGBoost**

In [ ]:
modelXGB = XGBRegressor(n_estimators=50, max_depth=15, min_samples_split=5, learning_rate=0.1, n_jobs=1, booster='gbtree')
resultsXGB = cross_validate(modelXGB, attributes, objectives, scoring=['neg_mean_absolute_error', 'r2'],
                            cv=10, n_jobs=-1, return_estimator=True, return_train_score=True)
print('MSE: ' + str(-resultsXGB['test_neg_mean_absolute_error'].mean()))
print('R2: ' + str(resultsXGB['test_r2'].mean()))
df_results = pd.DataFrame(resultsXGB)
df_results

In [ ]:
modelXGB2_1 = XGBRegressor(n_estimators=50, max_depth=15, min_samples_split=5, learning_rate=0.1, n_jobs=1, booster='gbtree')
resultsXGB2_1 = cross_validate(modelXGB2_1, attributes1, objectives1, scoring=['neg_mean_absolute_error', 'r2'], cv=10, n_jobs=-1, return_estimator=True, return_train_score=True)
print('MSE: ' + str(-resultsXGB2_1['test_neg_mean_absolute_error'].mean()))
print('R2: ' + str(resultsXGB2_1['test_r2'].mean()))
modelXGB2_2 = XGBRegressor(n_estimators=50, max_depth=15, min_samples_split=5, learning_rate=0.1, n_jobs=1, booster='gbtree')
resultsXGB2_2 = cross_validate(modelXGB2_2, attributes2, objectives2, scoring=['neg_mean_absolute_error', 'r2'], cv=10, n_jobs=-1, return_estimator=True, return_train_score=True)
print('MSE: ' + str(-resultsXGB2_2['test_neg_mean_absolute_error'].mean()))
print('R2: ' + str(resultsXGB2_2['test_r2'].mean()))

In [ ]:
pd.DataFrame(resultsXGB2_1)

In [ ]:
pd.DataFrame(resultsXGB2_2)