In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('dataset.csv', index_col=0)
data.head()

,P1,Q1,P2,Q2,P3,Q3,P4,Q4,P5,Q5,...,V7,V8,V9,V10,V11,V12,V13,V14,PERD,GWT7
day1_min0003,5.5235,2.72529,0.0,0.0,0.150708,0.060212,0.110339,0.068694,-0.338732,0.11529,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0000,-1.51,1.7324
day1_min0008,5.5235,2.72529,0.0,0.0,0.150708,0.060212,0.110339,0.068694,-0.338978,0.11529,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0000,0.00,0.0001
day1_min0013,5.4248,2.66419,0.0,0.0,0.148893,0.059087,0.107499,0.066933,-0.343748,0.11233,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0001,-25.84,0.4244
day1_min0018,5.3261,2.60299,0.0,0.0,0.147077,0.057961,0.104659,0.065172,-0.348518,0.10937,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0000,0.00,0.0000
day1_min0023,5.1700,2.50953,0.0,0.0,0.143958,0.056194,0.100389,0.062528,-0.355678,0.10494,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0000,0.00,-0.0002

**HISTOGRAMAS COLUMNAS**

In [3]:
data.loc[:,'P1':'Q14']

,P1,Q1,P2,Q2,P3,Q3,P4,Q4,P5,Q5,...,P10,Q10,P11,Q11,P12,Q12,P13,Q13,P14,Q14
day1_min0003,5.523500,2.725290,0.0,0.0,0.150708,0.060212,0.110339,0.068694,-0.338732,0.115290,...,-0.379584,0.080475,0.084677,0.052634,5.523500,2.725290,0.010719,0.002177,0.163652,0.055362
day1_min0008,5.523500,2.725290,0.0,0.0,0.150708,0.060212,0.110339,0.068694,-0.338978,0.115290,...,-0.379830,0.080475,0.084677,0.052634,5.523500,2.725290,0.010719,0.002177,0.163652,0.055362
day1_min0013,5.424800,2.664190,0.0,0.0,0.148893,0.059087,0.107499,0.066933,-0.343748,0.112330,...,-0.382970,0.078530,0.082500,0.051285,5.424800,2.664190,0.010719,0.002177,0.162291,0.054518
day1_min0018,5.326100,2.602990,0.0,0.0,0.147077,0.057961,0.104659,0.065172,-0.348518,0.109370,...,-0.386110,0.076585,0.080322,0.049935,5.326100,2.602990,0.010719,0.002177,0.160929,0.053674
day1_min0023,5.170000,2.509530,0.0,0.0,0.143958,0.056194,0.100389,0.062528,-0.355678,0.104940,...,-0.390932,0.073645,0.077054,0.047909,5.170000,2.509530,0.010667,0.002166,0.158345,0.052297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
day365_min1418,7.489982,3.371490,0.0,0.0,0.152071,0.062621,0.128159,0.079810,0.245566,0.181017,...,0.042157,0.096827,0.028095,0.043239,5.451247,3.065118,0.012039,0.002884,0.175465,0.047945
day365_min1423,3.438070,2.500200,0.0,0.0,0.187144,0.089657,0.103474,0.072299,-0.065346,0.127944,...,-0.023273,0.092830,0.044489,0.046578,6.072289,3.068960,0.010602,0.001993,0.244879,0.094290
day365_min1428,7.789884,3.344330,0.0,0.0,0.169649,0.071825,0.118070,0.074442,0.013488,0.152003,...,-0.091087,0.104760,0.100986,0.059673,4.643915,2.598569,0.002721,0.000000,0.153425,0.044861
day365_min1433,7.377037,3.232151,0.0,0.0,0.138669,0.060176,0.128430,0.076945,-0.240679,0.142487,...,-0.412306,0.080239,0.094905,0.057910,6.728277,3.095120,0.010524,0.002025,0.133142,0.036258
day365_min1438,5.169686,2.758862,0.0,0.0,0.126037,0.053849,0.115368,0.072758,-0.306772,0.123464,...,-0.343147,0.082934,0.154925,0.072396,3.885061,2.670432,0.017940,0.006668,0.217610,0.090026

In [4]:
data.loc[:,'V1':'GWT7']

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,PERD,GWT7
day1_min0003,1.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0,1.0,1.0000,-1.51,1.7324
day1_min0008,1.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0,1.0,1.0000,0.00,0.0001
day1_min0013,1.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0,1.0,1.0001,-25.84,0.4244
day1_min0018,1.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0,1.0,1.0000,0.00,0.0000
day1_min0023,1.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0,1.0,1.0000,0.00,-0.0002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
day365_min1418,1.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0,1.0,1.0000,0.00,0.0000
day365_min1423,1.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0,1.0,1.0000,0.00,0.0000
day365_min1428,1.0,1.0003,1.0004,1.0004,1.0004,1.0004,1.0004,1.0004,1.0004,1.0004,1.0004,1.0,1.0,1.0000,-166.95,5.7633
day365_min1433,1.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0,1.0,1.0000,-11.56,-5.8404
day365_min1438,1.0,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0,1.0,1.0000,0.00,0.0005

**ESTADÍSTICAS DE LAS COLUMNAS**

In [5]:
data.loc[:,'P1':'Q14'].describe()

,P1,Q1,P2,Q2,P3,Q3,P4,Q4,P5,Q5,...,P10,Q10,P11,Q11,P12,Q12,P13,Q13,P14,Q14
count,105120.000000,105120.000000,105120.0,105120.0,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,...,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000
mean,10.845736,5.456929,0.0,0.0,0.286946,0.118939,0.222951,0.139488,0.301679,0.233951,...,0.223825,0.162405,0.171402,0.106866,10.854012,5.459192,0.019407,0.003998,0.308067,0.108075
std,4.232609,2.148147,0.0,0.0,0.105938,0.045751,0.101523,0.058583,0.247745,0.098380,...,0.209016,0.066354,0.078088,0.044920,4.235169,2.150818,0.008573,0.002454,0.115912,0.042544
min,0.050046,0.842938,0.0,0.0,0.002446,0.005613,-0.005847,0.007693,-0.666508,0.022286,...,-0.558756,0.014014,-0.003495,0.004419,0.000000,0.531641,0.000000,0.000000,0.007386,0.005050
25%,7.111926,3.254189,0.0,0.0,0.190635,0.076985,0.141681,0.082160,0.177429,0.138167,...,0.129553,0.096989,0.108768,0.063119,7.131734,3.263096,0.012000,0.002128,0.205262,0.073677
50%,11.904757,6.030552,0.0,0.0,0.313761,0.130996,0.235659,0.151748,0.351824,0.254384,...,0.282155,0.177564,0.181352,0.116207,11.919392,6.037183,0.017964,0.003904,0.323918,0.115741
75%,14.185150,7.112406,0.0,0.0,0.370588,0.155247,0.297179,0.182183,0.467747,0.305797,...,0.362291,0.212243,0.229086,0.139649,14.196904,7.115503,0.027173,0.005738,0.403852,0.141038
max,21.591358,9.941682,0.0,0.0,0.538813,0.241552,0.540284,0.277295,0.909938,0.471233,...,0.673260,0.323484,0.439001,0.216232,21.833575,10.176398,0.044211,0.014372,0.604284,0.230962

In [6]:
data.loc[:,'V1':'GWT7'].describe()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,PERD,GWT7
count,105120.0,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000,105120.000000
mean,1.0,1.000173,1.000260,1.000260,1.000260,1.000260,1.000291,1.000291,1.000291,1.000291,1.000291,0.999999,1.000015,1.000024,-127.424375,1.319103
std,0.0,0.000513,0.000768,0.000768,0.000768,0.000768,0.000855,0.000854,0.000854,0.000854,0.000854,0.000010,0.000237,0.000337,433.334980,3.045297
min,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.999900,0.999900,0.999900,-5269.140000,-6.667200
25%,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-160.625000,-0.000325
50%,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-1.280000,0.045800
75%,1.0,1.000200,1.000400,1.000400,1.000400,1.000400,1.000400,1.000400,1.000400,1.000400,1.000400,1.000000,1.000000,1.000000,0.000000,3.596550
max,1.0,1.005400,1.008100,1.008100,1.008100,1.008100,1.009000,1.009000,1.009000,1.009000,1.009000,1.000000,1.004000,1.005700,0.000000,5.963600

**TRATAMIENTO INICIAL DATOS**

In [7]:
np.random.seed(357823)

In [8]:
attributes = data.iloc[:, :-16].drop(columns=['P2', 'Q2'])
objectives = data.iloc[:, 28:]

In [9]:
(training_attributes, test_attributes, training_objetive, test_objective) = train_test_split(attributes, objectives, test_size=0.2, random_state=42)

**ENTRENAMIENTO MODELOS INICIALES**

MODELO 1

In [10]:
model1 = RandomForestRegressor(n_estimators=50, max_depth=15, min_samples_split=5)
model1.fit(training_attributes, training_objetive)

RandomForestRegressor(max_depth=15, min_samples_split=5, n_estimators=50)

In [11]:
predictions = model1.predict(test_attributes)
print('MSE: ' + str(mean_squared_error(test_objective, predictions)))
print('R^2: ' + str(r2_score(test_objective, predictions)))
pd.DataFrame([mean_squared_error(test_objective, predictions, multioutput='raw_values')], columns=test_objective.columns)

MSE: 10944.71556995598
R^2: 0.15959774185049033

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,PERD,GWT7
0,0.0,2.402268e-07,5.377500e-07,5.377500e-07,5.376029e-07,5.376029e-07,6.657590e-07,6.654893e-07,6.654893e-07,6.654893e-07,6.654893e-07,8.933531e-11,5.397490e-08,1.090266e-07,175107.07748,8.371633

MODELO 2

In [12]:
attributes1 = data.iloc[:, :-16].drop(columns=['P2', 'Q2'])
objectives1 = data.iloc[:, -1:]
attributes2 = pd.concat([attributes1, objectives1], axis=1)
objectives2 = data.iloc[:, 28:-1]

In [13]:
(training_attributes1, test_attributes1, training_objetive1, test_objective1) = train_test_split(attributes1, objectives1, test_size=0.2, random_state=42)
(training_attributes2, test_attributes2, training_objetive2, test_objective2) = train_test_split(attributes2, objectives2, test_size=0.2, random_state=42)

In [25]:
model2_1 = RandomForestRegressor(n_estimators=50, max_depth=15, min_samples_split=5)
model2_1.fit(training_attributes1, training_objetive1.values.ravel())
model2_2 = RandomForestRegressor(n_estimators=50, max_depth=15, min_samples_split=5)
model2_2.fit(training_attributes2, training_objetive2)

RandomForestRegressor(max_depth=15, min_samples_split=5, n_estimators=50)

In [32]:
predictions1 = model2_1.predict(test_attributes1)
print('MSE: ' + str(mean_squared_error(test_objective1, predictions1)))
print('R^2: ' + str(r2_score(test_objective1, predictions1)))
pd.DataFrame([mean_squared_error(test_objective1, predictions1, multioutput='raw_values')], columns=test_objective1.columns)

MSE: 7.959625697327972
R^2: 0.149445145888928

       GWT7
0  7.959626

In [33]:
predictions2 = model2_2.predict(test_attributes2)
print('MSE: ' + str(mean_squared_error(test_objective2, predictions2)))
print('R^2: ' + str(r2_score(test_objective2, predictions2)))
pd.DataFrame([mean_squared_error(test_objective2, predictions2, multioutput='raw_values')], columns=test_objective2.columns)

MSE: 4.496788108452457
R^2: 0.9995399477741629

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,PERD
0,0.0,1.476304e-10,3.859982e-10,3.859982e-10,3.812085e-10,3.812085e-10,4.438129e-10,4.437240e-10,4.437240e-10,4.437240e-10,4.437240e-10,2.748182e-15,7.985693e-12,3.501277e-11,67.451822

EXPERIMENTO CON PRUEBA ALEATORIA

In [86]:
example_in = test_attributes2.iloc[49].to_frame().T.iloc[:, :-1]
example_out = test_objective2.iloc[49].to_frame().T
example_out

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,PERD
day327_min0443,1.0,1.0001,1.0001,1.0001,1.0001,1.0001,1.0001,1.0001,1.0001,1.0001,1.0001,1.0,1.0,1.0,-47.29

In [92]:
test_attributes2.iloc[49].to_frame().T.iloc[:, -1:]

                  GWT7
day327_min0443 -5.1474

In [100]:
example_prediction1 = model2_1.predict(example_in)
tmp = pd.DataFrame(example_prediction1, columns=['GWT7'], index=example_in.index) #Cambiar a -5.1474
example_in_2 = pd.concat([example_in, tmp], axis=1)
tmp

                    GWT7
day327_min0443  1.448204

In [99]:
pd.DataFrame(model2_2.predict(example_in_2), columns=example_out.columns, index=example_out.index)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,PERD
day327_min0443,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-15.84