In [23]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV, TimeSeriesSplit
from ElectricSequentialRegressor import ElectricSequentialRegressor
from scipy.stats import randint, uniform
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, mean_squared_error, r2_score, make_scorer
import joblib

<h2>Lectura y Tratamiento de Datos</h2>

In [2]:
X = pd.read_csv('dataset/dataset_in.txt', index_col=0).drop(columns=['P2', 'Q2'])
Y = pd.read_csv('dataset/dataset_out.txt', index_col=0).loc[:, ['PERD', 'QGEN7']]
normalizer_X = MinMaxScaler(feature_range=(0, 1))
X = pd.DataFrame(normalizer_X.fit_transform(X), columns=X.columns, index=X.index)
normalizer_Y = MinMaxScaler(feature_range=(0, 1))
Y = pd.DataFrame(normalizer_Y.fit_transform(Y), columns=Y.columns, index=Y.index)

**Validación por Retención (Tratamiento como Serie Temporal)**

In [3]:
n_samples = X.shape[0]
train_size = int(n_samples * 0.8)
x_train, y_train = X[:train_size], Y[:train_size]
x_test, y_test = X[train_size:], Y[train_size:]

<h2>Búsqueda Aleatoria de Hiperparámetros</h2>

In [4]:
random_model = ElectricSequentialRegressor(RandomForestRegressor(n_jobs=1, random_state=42), RandomForestRegressor(n_jobs=1, random_state=42))
random_grid = {
    'estimator1__n_estimators': randint(30, 101),
    'estimator1__max_depth': randint(10, 51),
    'estimator1__min_samples_split': randint(2, 21),
    'estimator1__max_features': uniform(0.1, 0.9),
    'estimator2__n_estimators': randint(80, 251),
    'estimator2__max_depth': randint(10, 51),
    'estimator2__min_samples_split': randint(2, 21),
    'estimator2__max_features': uniform(0.1, 0.9)
}
def mse_column_score(y_true, y_pred, col_idx):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    return mean_squared_error(y_true[:, col_idx], y_pred[:, col_idx])
random_scoring = {
    'mse_global': 'neg_mean_squared_error',
    'mse_perd': make_scorer(mse_column_score, col_idx=0, greater_is_better=False),
    'mse_qgen7': make_scorer(mse_column_score, col_idx=1, greater_is_better=False),
}
random_search = RandomizedSearchCV(random_model, random_grid, n_iter=30,
                                   cv=TimeSeriesSplit(n_splits=3), scoring=random_scoring, refit='mse_global',
                                   n_jobs=-1, verbose=2, random_state=42, return_train_score=True)

In [5]:
random_search.fit(x_train, y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits

RandomizedSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                   estimator=ElectricSequentialRegressor(estimator1=RandomForestRegressor(n_jobs=1,
                                                                                          random_state=42),
                                                         estimator2=RandomForestRegressor(n_jobs=1,
                                                                                          random_state=42)),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'estimator1__max_depth': <scipy.stats._distn_infrastructure.rv...
                                        'estimator2__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000023E55A90AD0>},
                   random_state=42, refit='mse_global', return_train_score=True,
                   scoring={'mse_global': 'neg_mean_squared_error',
                            'mse_perd': make_scorer(mse_column_score, greater_is_better=False, response_method='predict', col_idx=0),
                            'mse_qgen7': make_scorer(mse_column_score, greater_is_better=False, response_method='predict', col_idx=1)},
                   verbose=2)

In [6]:
best_random_model = random_search.best_estimator_
print('MSE: ' + str(random_search.best_score_))
pd.DataFrame(random_search.cv_results_).loc[:, ['param_estimator1__max_depth', 'param_estimator1__max_features', 'param_estimator1__min_samples_split', 'param_estimator1__n_estimators', 'param_estimator2__max_depth', 'param_estimator2__max_features', 'param_estimator2__min_samples_split', 'param_estimator2__n_estimators', 'mean_test_mse_global', 'mean_test_mse_perd', 'mean_test_mse_qgen7']]

MSE: -0.002169113083781005

,param_estimator1__max_depth,param_estimator1__max_features,param_estimator1__min_samples_split,param_estimator1__n_estimators,param_estimator2__max_depth,param_estimator2__max_features,param_estimator2__min_samples_split,param_estimator2__n_estimators,mean_test_mse_global,mean_test_mse_perd,mean_test_mse_qgen7
0,48,0.816889,16,90,30,0.240417,20,154,-0.002176,-0.000257,-0.004096
1,20,0.879559,5,53,12,0.118526,3,167,-0.002196,-0.000258,-0.004134
2,39,0.291105,2,87,31,0.106360,18,138,-0.002374,-0.000257,-0.004492
3,37,0.976380,16,91,12,0.873946,8,100,-0.002207,-0.000274,-0.004140
4,18,0.158546,5,89,23,0.827558,10,169,-0.003162,-0.000269,-0.006055
5,11,0.715810,16,89,16,0.648997,9,114,-0.002169,-0.000269,-0.004069
6,23,0.451955,19,33,11,0.482640,11,83,-0.002235,-0.000263,-0.004206
7,38,0.972626,13,63,19,0.905345,15,174,-0.002219,-0.000275,-0.004163
8,24,0.179643,9,82,33,0.421078,14,120,-0.003015,-0.000260,-0.005770
9,38,0.821977,2,100,18,0.795020,13,215,-0.002208,-0.000270,-0.004147
10,33,0.112672,20,37,44,0.811158,6,120,-0.005359,-0.000269,-0.010449
11,37,0.876793,9,41,43,0.185869,6,178,-0.002213,-0.000258,-0.004168
12,49,0.347250,4,94,44,0.207635,15,210,-0.002238,-0.000256,-0.004221
13,10,0.749557,15,56,18,0.739597,11,203,-0.002169,-0.000269,-0.004069
14,22,0.281547,8,81,41,0.725964,6,230,-0.002374,-0.000271,-0.004477
15,48,0.469345,12,58,45,0.948568,8,165,-0.002231,-0.000281,-0.004180
16,37,0.936728,14,91,15,0.510881,13,123,-0.002197,-0.000263,-0.004130
17,29,0.903303,12,91,42,0.344919,14,82,-0.002196,-0.000261,-0.004131
18,48,0.248190,10,91,46,0.723192,11,231,-0.002442,-0.000267,-0.004617
19,24,0.251462,10,81,21,0.326604,3,210,-0.002459,-0.000260,-0.004657
20,46,0.356356,18,88,11,0.552411,6,208,-0.002255,-0.000265,-0.004245
21,28,0.712635,13,61,15,0.317850,5,202,-0.002185,-0.000261,-0.004109
22,26,0.755395,6,99,31,0.582197,17,223,-0.002193,-0.000265,-0.004121
23,42,0.235646,7,32,29,0.393363,5,226,-0.002554,-0.000260,-0.004848
24,35,0.560884,20,49,41,0.186559,10,240,-0.002206,-0.000257,-0.004156
25,49,0.448062,19,30,20,0.406960,19,230,-0.002243,-0.000261,-0.004225
26,40,0.889605,4,36,25,0.835500,18,81,-0.002232,-0.000273,-0.004190
27,10,0.183792,13,98,46,0.894373,10,178,-0.004491,-0.000274,-0.008708
28,28,0.753360,4,49,33,0.464057,2,231,-0.002212,-0.000266,-0.004158
29,20,0.942071,5,67,49,0.645786,4,191,-0.002213,-0.000271,-0.004155

In [7]:
random_predictions = best_random_model.predict(x_test)
random_data_score = np.vstack([mean_absolute_error(y_test, random_predictions, multioutput='raw_values').reshape(1,-1),
                              mean_absolute_percentage_error(y_test, random_predictions, multioutput='raw_values').reshape(1,-1),
                              r2_score(y_test, random_predictions, multioutput='raw_values').reshape(1,-1)])
pd.DataFrame(random_data_score, columns=['PERD', 'QGEN7'], index=['MAE', 'MAPE', 'R2'])

          PERD         QGEN7
MAE   0.001261  2.302592e-02
MAPE  0.001958  1.932416e+11
R2   -0.027052  8.849713e-01

<h2>Búsqueda Exhaustiva de Hiperparámetros</h2>

In [17]:
grid_model = ElectricSequentialRegressor(RandomForestRegressor(n_jobs=1, random_state=42), RandomForestRegressor(min_samples_split=18, max_features=0.18, n_jobs=1, random_state=42))
grid = {
    'estimator1__n_estimators': range(80, 90, 5),
    'estimator1__max_depth': range(22, 34, 4),
    'estimator2__n_estimators': range(140, 180, 10),
    'estimator2__max_depth': range(30, 44, 4),
}
def mse_column_score(y_true, y_pred, col_idx):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    return mean_squared_error(y_true[:, col_idx], y_pred[:, col_idx])
grid_scoring = {
    'mse_global': 'neg_mean_squared_error',
    'mse_perd': make_scorer(mse_column_score, col_idx=0, greater_is_better=False),
    'mse_qgen7': make_scorer(mse_column_score, col_idx=1, greater_is_better=False),
}
grid_search = GridSearchCV(grid_model, grid, scoring=grid_scoring, cv=TimeSeriesSplit(n_splits=3), n_jobs=-1, verbose=2, return_train_score=True, refit='mse_global')

In [18]:
grid_search.fit(x_train, y_train)

Fitting 3 folds for each of 96 candidates, totalling 288 fits

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
             estimator=ElectricSequentialRegressor(estimator1=RandomForestRegressor(n_jobs=1,
                                                                                    random_state=42),
                                                   estimator2=RandomForestRegressor(max_features=0.18,
                                                                                    min_samples_split=18,
                                                                                    n_jobs=1,
                                                                                    random_state=42)),
             n_jobs=-1,
             param_grid={'estimator1__max_depth': range(22, 34, 4),
                         'estimat...
                         'estimator2__n_estimators': range(140, 180, 10)},
             refit='mse_global', return_train_score=True,
             scoring={'mse_global': 'neg_mean_squared_error',
                      'mse_perd': make_scorer(mse_column_score, greater_is_better=False, response_method='predict', col_idx=0),
                      'mse_qgen7': make_scorer(mse_column_score, greater_is_better=False, response_method='predict', col_idx=1)},
             verbose=2)

In [20]:
best_grid_model = grid_search.best_estimator_
print('MSE: ' + str(grid_search.best_score_))
pd.DataFrame(grid_search.cv_results_).loc[:, ['param_estimator1__max_depth', 'param_estimator1__n_estimators', 'param_estimator2__max_depth', 'param_estimator2__n_estimators', 'mean_test_mse_global', 'mean_test_mse_perd', 'mean_test_mse_qgen7']]

MSE: -0.0022180536560117065

,param_estimator1__max_depth,param_estimator1__n_estimators,param_estimator2__max_depth,param_estimator2__n_estimators,mean_test_mse_global,mean_test_mse_perd,mean_test_mse_qgen7
0,22,80,30,140,-0.002219,-0.000257,-0.004182
1,22,80,30,150,-0.002219,-0.000256,-0.004182
2,22,80,30,160,-0.002219,-0.000256,-0.004182
3,22,80,30,170,-0.002219,-0.000256,-0.004182
4,22,80,34,140,-0.002219,-0.000256,-0.004182
...,...,...,...,...,...,...,...
91,30,85,38,170,-0.002224,-0.000256,-0.004193
92,30,85,42,140,-0.002224,-0.000256,-0.004193
93,30,85,42,150,-0.002224,-0.000256,-0.004193
94,30,85,42,160,-0.002224,-0.000256,-0.004193
95,30,85,42,170,-0.002224,-0.000256,-0.004193

In [21]:
grid_predictions = best_grid_model.predict(x_test)
grid_data_score = np.vstack([mean_absolute_error(y_test, grid_predictions, multioutput='raw_values').reshape(1,-1),
                              mean_absolute_percentage_error(y_test, grid_predictions, multioutput='raw_values').reshape(1,-1),
                              r2_score(y_test, grid_predictions, multioutput='raw_values').reshape(1,-1)])
pd.DataFrame(grid_data_score, columns=['PERD', 'QGEN7'], index=['MAE', 'MAPE', 'R2'])

          PERD         QGEN7
MAE   0.001192  2.332025e-02
MAPE  0.001901  1.958715e+11
R2    0.014007  8.824678e-01

In [24]:
joblib.dump(best_grid_model, 'modelos/ESR_RandomForest.pkl')

['modelos/ESR_RandomForest.pkl']