In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error, r2_score
from metagen.framework import Domain
from metagen.metaheuristics.rs import RandomSearch

In [2]:
X = pd.read_csv('../dataset/dataset_in.txt', index_col=0).drop(columns=['P2', 'Q2'])
y_columns = [f'V{i}' for i in range(2,15)] + ['PERD', 'QGEN7'] #V1 ES SIEMPRE 1.0 EN DATASET
Y = pd.read_csv('../dataset/dataset_out.txt', index_col=0).loc[:, y_columns]
#FILTRAR DATOS ERRÓNEOS (PÉRDIDAS NEGATIVAS)
mask = Y['PERD'] >= 0
X = X[mask]
Y = Y[mask]

In [3]:
# VALIDACIÓN POR RETENCIÓN PARA EVALUACIÓN FINAL DEL MEJOR MODELO
n_samples = X.shape[0]
train_size = int(n_samples * 0.8)
x_train, y_train = X[:train_size], Y[:train_size]
x_test, y_test = X[train_size:], Y[train_size:]

In [4]:
NN_domain = Domain()
NN_domain.define_categorical("activation", ["relu", "elu"])
NN_domain.define_real("dropout", 0.0, 0.3)
NN_domain.define_categorical("use_batch_norm", [True, False])
NN_domain.define_real("learning_rate", 1e-4, 1e-2)
NN_domain.define_categorical("optimizer", ["sgd", "adam"])
NN_domain.define_integer("n_hidden_q", 1, 3)
NN_domain.define_integer("n_neurons_q", 32, 128)
NN_domain.define_integer("n_hidden_v", 1, 2)
NN_domain.define_integer("n_neurons_v", 64, 256)
NN_domain.define_integer("n_hidden_p", 2, 5)
NN_domain.define_integer("n_neurons_p", 64, 256)

In [5]:
def build_meta_neural_network(solution, input_dim, num_voltages):
    inputs = tf.keras.Input(shape=(input_dim,), name='input_x')
    x_norm = inputs

    activation = solution["activation"]
    dropout_rate = solution["dropout"]
    use_batch_norm = solution["use_batch_norm"]

    if solution["optimizer"] == 'sgd':
        optimizer = tf.keras.optimizers.SGD(learning_rate=solution["learning_rate"])
    else:
        optimizer = tf.keras.optimizers.Adam(learning_rate=solution["learning_rate"])

    x1 = x_norm
    for _ in range(solution["n_hidden_q"]):
        x1 = tf.keras.layers.Dense(solution["n_neurons_q"])(x1)
        if use_batch_norm: x1 = tf.keras.layers.BatchNormalization()(x1)
        x1 = tf.keras.layers.Activation(activation)(x1)
        if dropout_rate > 0: x1 = tf.keras.layers.Dropout(dropout_rate)(x1)

    out_qgen = tf.keras.layers.Dense(1, activation='linear', name='out_qgen7')(x1)
    merged = tf.keras.layers.Concatenate()([x_norm, out_qgen])

    x2 = merged
    for _ in range(solution["n_hidden_v"]):
        x2 = tf.keras.layers.Dense(solution["n_neurons_v"])(x2)
        if use_batch_norm: x2 = tf.keras.layers.BatchNormalization()(x2)
        x2 = tf.keras.layers.Activation(activation)(x2)
        if dropout_rate > 0: x2 = tf.keras.layers.Dropout(dropout_rate)(x2)

    out_v = tf.keras.layers.Dense(num_voltages, activation='linear', name='out_volt')(x2)

    x3 = merged
    for _ in range(solution["n_hidden_p"]):
        x3 = tf.keras.layers.Dense(solution["n_neurons_p"])(x3)
        if use_batch_norm: x3 = tf.keras.layers.BatchNormalization()(x3)
        x3 = tf.keras.layers.Activation(activation)(x3)
        if dropout_rate > 0: x3 = tf.keras.layers.Dropout(dropout_rate)(x3)

    out_perd = tf.keras.layers.Dense(1, activation='linear', name='out_perd')(x3)

    model = tf.keras.Model(inputs=inputs, outputs=[out_v, out_perd, out_qgen])

    model.compile(
        optimizer=optimizer,
        loss_weights={'out_qgen7': 1.0, 'out_volt': 1.0, 'out_perd': 2.0},
        loss={'out_qgen7': 'mse', 'out_volt': 'mse', 'out_perd': 'mse'},
        metrics={'out_qgen7': ['mae', 'mape', tf.keras.metrics.R2Score(name='r2_score')],
            'out_volt': ['mae', 'mape', tf.keras.metrics.R2Score(name='r2_score')],
            'out_perd': ['mae', 'mape', tf.keras.metrics.R2Score(name='r2_score')]},
    )
    return model

In [6]:
def build_nn_fitness(num_volts, idx_perd, idx_qgen, idx_volts, x, y):
    def nn_fitness(solution):
        model = build_meta_neural_network(solution, input_dim=x.shape[1], num_voltages=num_volts)
        tscv = TimeSeriesSplit(n_splits=5)

        val_losses = []

        for train_index, test_index in tscv.split(x):
            x_tr, x_val = x.iloc[train_index], x.iloc[test_index]
            y_tr, y_val = y.iloc[train_index], y.iloc[test_index]

            scaler_x_fold = MinMaxScaler()
            scaler_y_fold = MinMaxScaler()

            xs_tr = scaler_x_fold.fit_transform(x_tr)
            ys_tr = scaler_y_fold.fit_transform(y_tr)

            xs_val = scaler_x_fold.transform(x_val)
            ys_val = scaler_y_fold.transform(y_val)

            dict_y_tr = {
                'out_volt': ys_tr[:, idx_volts],
                'out_perd': ys_tr[:, idx_perd:idx_perd+1],
                'out_qgen7': ys_tr[:, idx_qgen:idx_qgen+1]
            }
            dict_y_val = {
                'out_volt': ys_val[:, idx_volts],
                'out_perd': ys_val[:, idx_perd:idx_perd+1],
                'out_qgen7': ys_val[:, idx_qgen:idx_qgen+1]
            }

            stop_early = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

            model.fit(xs_tr, dict_y_tr, validation_data=(xs_val, dict_y_val),
                      epochs=15, batch_size=256, verbose=0, callbacks=[stop_early])

            metrics = model.evaluate(xs_val, dict_y_val, verbose=0, return_dict=True)
            val_losses.append(metrics['loss'])

        return np.mean(val_losses)
    return nn_fitness

In [7]:
volts = len([c for c in Y.columns if c.startswith('V')])
idx_v = [Y.columns.get_loc(c) for c in Y.columns if c.startswith('V')]
idx_p = Y.columns.get_loc('PERD')
idx_q = Y.columns.get_loc('QGEN7')

In [8]:
fitness = build_nn_fitness(volts, idx_p, idx_q, idx_v, x_train, y_train)
NN_solution = RandomSearch(NN_domain, fitness, population_size=2, max_iterations=20).run()
print(NN_solution)

F = 0.00877946736291051	{activation = relu , dropout = 0.13057230112028143 , learning_rate = 0.0041609884009389435 , n_hidden_p = 4 , n_hidden_q = 3 , n_hidden_v = 2 , n_neurons_p = 131 , n_neurons_q = 121 , n_neurons_v = 96 , optimizer = adam , use_batch_norm = True}

In [9]:
best_model = build_meta_neural_network(NN_solution, input_dim=x_train.shape[1], num_voltages=volts)

In [10]:
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

xs_train = scaler_x.fit_transform(x_train)
ys_train = scaler_y.fit_transform(y_train)
xs_test = scaler_x.transform(x_test)

dict_y_train = {
    'out_volt': ys_train[:, idx_v],
    'out_perd': ys_train[:, idx_p:idx_p+1],
    'out_qgen7': ys_train[:, idx_q:idx_q+1]
}

In [11]:
stop_early_final = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=5, restore_best_weights=True)
best_model.fit(xs_train, dict_y_train, epochs=30, batch_size=256, verbose=1, callbacks=[stop_early_final])

Epoch 1/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - loss: 0.3308 - out_perd_loss: 0.0743 - out_perd_mae: 0.1582 - out_perd_mape: 987.0649 - out_perd_r2_score: -8.7954 - out_qgen7_loss: 0.1269 - out_qgen7_mae: 0.2398 - out_qgen7_mape: 10780.1328 - out_qgen7_r2_score: -2.2914 - out_volt_loss: 0.0551 - out_volt_mae: 0.1466 - out_volt_mape: 3061.7300 - out_volt_r2_score: -2.5833
Epoch 2/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0276 - out_perd_loss: 0.0026 - out_perd_mae: 0.0390 - out_perd_mape: 96.0575 - out_perd_r2_score: 0.6530 - out_qgen7_loss: 0.0174 - out_qgen7_mae: 0.0948 - out_qgen7_mape: 8672.2119 - out_qgen7_r2_score: 0.5498 - out_volt_loss: 0.0050 - out_volt_mae: 0.0536 - out_volt_mape: 2465.5591 - out_volt_r2_score: 0.6827
Epoch 3/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0162 - out_perd_loss: 9.4320e-04 - out_perd_mae: 0.0234 - out_perd_mape: 492.1649 - out_perd_r2_score: 0.8757 - out_qgen7_loss: 0.0118 - out_qgen7_mae: 0.0730 - out_qgen7_mape: 9651.7383 - out_qgen7_r2_score: 0.6934 - out_volt_loss: 0.0025 - out_volt_mae: 0.0383 - out_volt_mape: 2107.0056 - out_volt_r2_score: 0.8426
Epoch 4/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0139 - out_perd_loss: 6.6870e-04 - out_perd_mae: 0.0196 - out_perd_mape: 114.7235 - out_perd_r2_score: 0.9119 - out_qgen7_loss: 0.0108 - out_qgen7_mae: 0.0679 - out_qgen7_mape: 11402.9121 - out_qgen7_r2_score: 0.7197 - out_volt_loss: 0.0017 - out_volt_mae: 0.0318 - out_volt_mape: 2232.9111 - out_volt_r2_score: 0.8924
Epoch 5/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0122 - out_perd_loss: 5.5985e-04 - out_perd_mae: 0.0178 - out_perd_mape: 61.0568 - out_perd_r2_score: 0.9262 - out_qgen7_loss: 0.0098 - out_qgen7_mae: 0.0623 - out_qgen7_mape: 9339.0000 - out_qgen7_r2_score: 0.7462 - out_volt_loss: 0.0013 - out_volt_mae: 0.0283 - out_volt_mape: 1596.3225 - out_volt_r2_score: 0.9162
Epoch 6/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0115 - out_perd_loss: 4.8388e-04 - out_perd_mae: 0.0167 - out_perd_mape: 154.9087 - out_perd_r2_score: 0.9362 - out_qgen7_loss: 0.0094 - out_qgen7_mae: 0.0606 - out_qgen7_mape: 9891.8760 - out_qgen7_r2_score: 0.7563 - out_volt_loss: 0.0011 - out_volt_mae: 0.0257 - out_volt_mape: 2202.5977 - out_volt_r2_score: 0.9309
Epoch 7/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0109 - out_perd_loss: 4.4428e-04 - out_perd_mae: 0.0159 - out_perd_mape: 139.2822 - out_perd_r2_score: 0.9415 - out_qgen7_loss: 0.0090 - out_qgen7_mae: 0.0587 - out_qgen7_mape: 10106.4414 - out_qgen7_r2_score: 0.7671 - out_volt_loss: 0.0010 - out_volt_mae: 0.0246 - out_volt_mape: 1260.1178 - out_volt_r2_score: 0.9370
Epoch 8/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0107 - out_perd_loss: 4.1384e-04 - out_perd_mae: 0.0154 - out_perd_mape: 57.0448 - out_perd_r2_score: 0.9455 - out_qgen7_loss: 0.0089 - out_qgen7_mae: 0.0579 - out_qgen7_mape: 10088.0840 - out_qgen7_r2_score: 0.7701 - out_volt_loss: 9.6115e-04 - out_volt_mae: 0.0241 - out_volt_mape: 2881.5371 - out_volt_r2_score: 0.9393
Epoch 9/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0101 - out_perd_loss: 4.4068e-04 - out_perd_mae: 0.0159 - out_perd_mape: 263.6414 - out_perd_r2_score: 0.9419 - out_qgen7_loss: 0.0084 - out_qgen7_mae: 0.0550 - out_qgen7_mape: 10964.8682 - out_qgen7_r2_score: 0.7835 - out_volt_loss: 8.9962e-04 - out_volt_mae: 0.0234 - out_volt_mape: 556.2197 - out_volt_r2_score: 0.9430
Epoch 10/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0100 - out_perd_loss: 4.9023e-04 - out_perd_mae: 0.0169 - out_perd_mape: 342.0193 - out_perd_r2_score: 0.9354 - out_qgen7_loss: 0.0081 - out_qgen7_mae: 0.0540 - out_qgen7_mape: 10333.5283 - out_qgen7_r2_score: 0.7888 - out_volt_loss: 9.0304e-04 - out_volt_mae: 0.0234 - out_volt_mape: 406.4620 - out_volt_r2_score: 0.9425
Epoch 11/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0097 - out_perd_loss: 4.6123e-04 - out_perd_mae: 0.0163 - out_perd_mape: 411.9554 - out_perd_r2_score: 0.9392 - out_qgen7_loss: 0.0079 - out_qgen7_mae: 0.0527 - out_qgen7_mape: 10272.1895 - out_qgen7_r2_score: 0.7950 - out_volt_loss: 8.4195e-04 - out_volt_mae: 0.0226 - out_volt_mape: 205.7945 - out_volt_r2_score: 0.9464
Epoch 12/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0097 - out_perd_loss: 4.2513e-04 - out_perd_mae: 0.0158 - out_perd_mape: 41.5817 - out_perd_r2_score: 0.9440 - out_qgen7_loss: 0.0080 - out_qgen7_mae: 0.0537 - out_qgen7_mape: 10109.6953 - out_qgen7_r2_score: 0.7927 - out_volt_loss: 8.2671e-04 - out_volt_mae: 0.0224 - out_volt_mape: 580.4753 - out_volt_r2_score: 0.9474
Epoch 13/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0093 - out_perd_loss: 4.2718e-04 - out_perd_mae: 0.0158 - out_perd_mape: 565.2988 - out_perd_r2_score: 0.9437 - out_qgen7_loss: 0.0076 - out_qgen7_mae: 0.0509 - out_qgen7_mape: 10970.0283 - out_qgen7_r2_score: 0.8036 - out_volt_loss: 8.3231e-04 - out_volt_mae: 0.0225 - out_volt_mape: 636.5101 - out_volt_r2_score: 0.9467
Epoch 14/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0094 - out_perd_loss: 4.1843e-04 - out_perd_mae: 0.0157 - out_perd_mape: 766.9821 - out_perd_r2_score: 0.9449 - out_qgen7_loss: 0.0078 - out_qgen7_mae: 0.0529 - out_qgen7_mape: 10056.0869 - out_qgen7_r2_score: 0.7986 - out_volt_loss: 7.8895e-04 - out_volt_mae: 0.0218 - out_volt_mape: 563.1423 - out_volt_r2_score: 0.9496
Epoch 15/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0089 - out_perd_loss: 3.2405e-04 - out_perd_mae: 0.0135 - out_perd_mape: 72.4849 - out_perd_r2_score: 0.9573 - out_qgen7_loss: 0.0075 - out_qgen7_mae: 0.0502 - out_qgen7_mape: 10199.1279 - out_qgen7_r2_score: 0.8062 - out_volt_loss: 7.8825e-04 - out_volt_mae: 0.0218 - out_volt_mape: 835.4470 - out_volt_r2_score: 0.9496
Epoch 16/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0089 - out_perd_loss: 3.9431e-04 - out_perd_mae: 0.0151 - out_perd_mape: 757.7849 - out_perd_r2_score: 0.9480 - out_qgen7_loss: 0.0073 - out_qgen7_mae: 0.0493 - out_qgen7_mape: 11021.3926 - out_qgen7_r2_score: 0.8102 - out_volt_loss: 8.0357e-04 - out_volt_mae: 0.0220 - out_volt_mape: 1477.8638 - out_volt_r2_score: 0.9487
Epoch 17/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0087 - out_perd_loss: 3.6611e-04 - out_perd_mae: 0.0144 - out_perd_mape: 512.0070 - out_perd_r2_score: 0.9518 - out_qgen7_loss: 0.0072 - out_qgen7_mae: 0.0484 - out_qgen7_mape: 10002.3623 - out_qgen7_r2_score: 0.8132 - out_volt_loss: 8.1332e-04 - out_volt_mae: 0.0222 - out_volt_mape: 775.4465 - out_volt_r2_score: 0.9479
Epoch 18/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0085 - out_perd_loss: 3.1905e-04 - out_perd_mae: 0.0134 - out_perd_mape: 199.6660 - out_perd_r2_score: 0.9580 - out_qgen7_loss: 0.0071 - out_qgen7_mae: 0.0478 - out_qgen7_mape: 10529.2832 - out_qgen7_r2_score: 0.8162 - out_volt_loss: 7.8230e-04 - out_volt_mae: 0.0217 - out_volt_mape: 1239.6765 - out_volt_r2_score: 0.9499
Epoch 19/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0085 - out_perd_loss: 3.1149e-04 - out_perd_mae: 0.0131 - out_perd_mape: 306.7170 - out_perd_r2_score: 0.9590 - out_qgen7_loss: 0.0072 - out_qgen7_mae: 0.0479 - out_qgen7_mape: 10186.0000 - out_qgen7_r2_score: 0.8145 - out_volt_loss: 7.6300e-04 - out_volt_mae: 0.0215 - out_volt_mape: 292.1490 - out_volt_r2_score: 0.9511
Epoch 20/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0085 - out_perd_loss: 2.7532e-04 - out_perd_mae: 0.0123 - out_perd_mape: 461.1747 - out_perd_r2_score: 0.9637 - out_qgen7_loss: 0.0071 - out_qgen7_mae: 0.0482 - out_qgen7_mape: 10932.2793 - out_qgen7_r2_score: 0.8147 - out_volt_loss: 7.5721e-04 - out_volt_mae: 0.0214 - out_volt_mape: 1541.9797 - out_volt_r2_score: 0.9514
Epoch 21/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0083 - out_perd_loss: 2.8615e-04 - out_perd_mae: 0.0124 - out_perd_mape: 305.1134 - out_perd_r2_score: 0.9623 - out_qgen7_loss: 0.0069 - out_qgen7_mae: 0.0460 - out_qgen7_mape: 10364.9189 - out_qgen7_r2_score: 0.8205 - out_volt_loss: 7.5677e-04 - out_volt_mae: 0.0213 - out_volt_mape: 1165.5665 - out_volt_r2_score: 0.9514
Epoch 22/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0082 - out_perd_loss: 2.8901e-04 - out_perd_mae: 0.0125 - out_perd_mape: 840.9329 - out_perd_r2_score: 0.9619 - out_qgen7_loss: 0.0068 - out_qgen7_mae: 0.0460 - out_qgen7_mape: 10116.9590 - out_qgen7_r2_score: 0.8228 - out_volt_loss: 7.7437e-04 - out_volt_mae: 0.0216 - out_volt_mape: 737.2889 - out_volt_r2_score: 0.9501
Epoch 23/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0080 - out_perd_loss: 2.5988e-04 - out_perd_mae: 0.0118 - out_perd_mape: 199.3528 - out_perd_r2_score: 0.9658 - out_qgen7_loss: 0.0067 - out_qgen7_mae: 0.0445 - out_qgen7_mape: 10137.2969 - out_qgen7_r2_score: 0.8268 - out_volt_loss: 7.5990e-04 - out_volt_mae: 0.0214 - out_volt_mape: 1787.3868 - out_volt_r2_score: 0.9511
Epoch 24/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0080 - out_perd_loss: 2.6048e-04 - out_perd_mae: 0.0117 - out_perd_mape: 85.3361 - out_perd_r2_score: 0.9657 - out_qgen7_loss: 0.0067 - out_qgen7_mae: 0.0452 - out_qgen7_mape: 10059.9150 - out_qgen7_r2_score: 0.8265 - out_volt_loss: 7.5582e-04 - out_volt_mae: 0.0213 - out_volt_mape: 673.9323 - out_volt_r2_score: 0.9513
Epoch 25/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0078 - out_perd_loss: 2.5242e-04 - out_perd_mae: 0.0116 - out_perd_mape: 439.4516 - out_perd_r2_score: 0.9667 - out_qgen7_loss: 0.0066 - out_qgen7_mae: 0.0439 - out_qgen7_mape: 9970.4902 - out_qgen7_r2_score: 0.8286 - out_volt_loss: 7.2821e-04 - out_volt_mae: 0.0209 - out_volt_mape: 2098.0986 - out_volt_r2_score: 0.9532
Epoch 26/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0078 - out_perd_loss: 2.6134e-04 - out_perd_mae: 0.0118 - out_perd_mape: 411.5502 - out_perd_r2_score: 0.9656 - out_qgen7_loss: 0.0065 - out_qgen7_mae: 0.0435 - out_qgen7_mape: 10130.4502 - out_qgen7_r2_score: 0.8305 - out_volt_loss: 7.4139e-04 - out_volt_mae: 0.0211 - out_volt_mape: 789.3136 - out_volt_r2_score: 0.9523
Epoch 27/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0077 - out_perd_loss: 2.2922e-04 - out_perd_mae: 0.0110 - out_perd_mape: 188.4636 - out_perd_r2_score: 0.9698 - out_qgen7_loss: 0.0065 - out_qgen7_mae: 0.0438 - out_qgen7_mape: 10647.8594 - out_qgen7_r2_score: 0.8308 - out_volt_loss: 7.1005e-04 - out_volt_mae: 0.0207 - out_volt_mape: 1225.3674 - out_volt_r2_score: 0.9542
Epoch 28/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0076 - out_perd_loss: 2.3571e-04 - out_perd_mae: 0.0111 - out_perd_mape: 372.4427 - out_perd_r2_score: 0.9689 - out_qgen7_loss: 0.0064 - out_qgen7_mae: 0.0432 - out_qgen7_mape: 10447.6885 - out_qgen7_r2_score: 0.8337 - out_volt_loss: 7.2632e-04 - out_volt_mae: 0.0210 - out_volt_mape: 1383.7820 - out_volt_r2_score: 0.9533
Epoch 29/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0074 - out_perd_loss: 2.1456e-04 - out_perd_mae: 0.0106 - out_perd_mape: 362.1147 - out_perd_r2_score: 0.9717 - out_qgen7_loss: 0.0063 - out_qgen7_mae: 0.0429 - out_qgen7_mape: 10343.4150 - out_qgen7_r2_score: 0.8366 - out_volt_loss: 6.7874e-04 - out_volt_mae: 0.0203 - out_volt_mape: 660.2169 - out_volt_r2_score: 0.9564
Epoch 30/30
328/328 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0074 - out_perd_loss: 2.3398e-04 - out_perd_mae: 0.0111 - out_perd_mape: 498.9871 - out_perd_r2_score: 0.9692 - out_qgen7_loss: 0.0062 - out_qgen7_mae: 0.0427 - out_qgen7_mape: 10171.4238 - out_qgen7_r2_score: 0.8380 - out_volt_loss: 6.9646e-04 - out_volt_mae: 0.0206 - out_volt_mape: 630.5225 - out_volt_r2_score: 0.9550

In [12]:
preds_list = best_model.predict(xs_test)
preds_concat = np.hstack([preds_list[0], preds_list[1], preds_list[2]])
predictions = scaler_y.inverse_transform(preds_concat)

656/656 ━━━━━━━━━━━━━━━━━━━━ 1s 778us/step

In [13]:
random_MAE = mean_absolute_error(y_test, predictions, multioutput='raw_values')
random_MAPE = mean_absolute_percentage_error(y_test, predictions, multioutput='raw_values')

# DESPLAZAMIENTO PARA EVITAR DIVISIÓN POR VALORES CERCANO A 0. CONSECUENCIA: MAPE ALGO OPTIMISTA
random_MAPE_shifted = mean_absolute_percentage_error(y_test + 1.0, predictions + 1.0, multioutput='raw_values')
random_R2 = r2_score(y_test, predictions, multioutput='raw_values')

In [14]:
print("\n--- RESULTADOS CON MAPE DESPLAZADO ---")
random_data_score_shifted = np.vstack([random_MAE, random_MAPE_shifted, random_R2])
evaluations_shifted = pd.DataFrame(random_data_score_shifted, columns=y_columns, index=['MAE', 'MAPE', 'R2'])
display(evaluations_shifted)

print("\n--- RESULTADOS SIN DESPLAZAMIENTO ---")
random_data_score = np.vstack([random_MAE, random_MAPE, random_R2])
evaluations = pd.DataFrame(random_data_score, columns=y_columns, index=['MAE', 'MAPE', 'R2'])
display(evaluations)

--- RESULTADOS CON MAPE DESPLAZADO ---

,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,PERD,QGEN7
MAE,0.002149,0.002154,0.002156,0.002148,0.002154,0.002154,0.002154,0.002155,0.002156,0.002157,0.002157,0.001535,0.001532,0.299521,0.009180
MAPE,0.001088,0.001091,0.001092,0.001088,0.001091,0.001091,0.001091,0.001092,0.001092,0.001092,0.001093,0.000774,0.000773,0.031811,0.008594
R2,0.961254,0.961718,0.961977,0.962241,0.962102,0.962142,0.962082,0.962070,0.962052,0.962044,0.962037,0.975087,0.975182,0.968692,0.843725

--- RESULTADOS SIN DESPLAZAMIENTO ---

,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,PERD,QGEN7
MAE,0.002149,0.002154,0.002156,0.002148,0.002154,0.002154,0.002154,0.002155,0.002156,0.002157,0.002157,0.001535,0.001532,0.299521,9.180139e-03
MAPE,0.002204,0.002210,0.002213,0.002206,0.002211,0.002212,0.002212,0.002212,0.002213,0.002214,0.002214,0.001563,0.001559,0.037285,1.351303e+13
R2,0.961254,0.961718,0.961977,0.962241,0.962102,0.962142,0.962082,0.962070,0.962052,0.962044,0.962037,0.975087,0.975182,0.968692,8.437254e-01

In [15]:
# EVALUACIÓN FINAL CON MEDIA DE VOLTAJES (MAPE DESPLAZADO)
volts_columns = [c for c in y_train.columns if c.startswith('V')]
pd.DataFrame({
    'Voltajes (Desplazados)': evaluations_shifted[volts_columns].mean(axis=1),
    'Pérdidas (Desplazada)': evaluations_shifted['PERD'],
    'Potencia Reactiva (Desplazada)': evaluations_shifted['QGEN7']
})

,Voltajes (Desplazados),Pérdidas (Desplazada),Potencia Reactiva (Desplazada)
MAE,0.002058,0.299521,0.009180
MAPE,0.001042,0.031811,0.008594
R2,0.963999,0.968692,0.843725

In [16]:
# EVALUACIÓN FINAL CON MEDIA DE VOLTAJES (MAPE SIN DESPLAZAMIENTO)
pd.DataFrame({
    'Voltajes': evaluations[volts_columns].mean(axis=1),
    'Pérdidas': evaluations['PERD'],
    'Potencia Reactiva': evaluations['QGEN7']
})

      Voltajes  Pérdidas  Potencia Reactiva
MAE   0.002058  0.299521       9.180139e-03
MAPE  0.002111  0.037285       1.351303e+13
R2    0.963999  0.968692       8.437254e-01